[workspace]
members = [
    "sheets_database",
    "sheets_database_derive",
    "test_suite"
]
resolver = "2"

[workspace.dependencies]
google-sheets4 = "5.0.3+20230119"
proc-macro2 = "1.0.78"
quote = "1.0"
syn = { version = "2.0.48", default-features = false }
