site_name: Test docs
site_description: ""
site_author: "Klemen Kobau"
docs_dir: docs/
repo_name: "KlemenKobau/Sheets-database"
repo_url: "https://github.com/KlemenKobau/Sheets-database"
nav:
  - Home: index.md
theme:
  name: "material"
